config/routes.rb
Rails.application.routes.draw do
  resources :deputies, only: [:index, :show]

  root 'deputies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deputy.rb
# == Schema Information
#
# Table name: deputies
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  cpf             :string
#  deputy_id       :integer
#  legislature_id  :integer
#  state           :string(2)
#  political_party :string
#  photo_url       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Deputy < ApplicationRecord
  has_many :expenses

  def self.with_total_expenses
    Deputy.joins(:expenses)
          .select('deputies.*, sum(expenses.net_value) as total_expenses')
          .group('deputies.id')
  end

  def max_expense
    expenses.order(net_value: :desc).first
  end
end

app/models/expense.rb
# == Schema Information
#
# Table name: expenses
#
#  id               :integer          not null, primary key
#  deputy_id        :integer          not null
#  expense_type_id  :integer          not null
#  provider_id      :integer          not null
#  year             :integer
#  month            :integer
#  document_code    :integer
#  document_number  :string
#  document_type    :string
#  document_type_id :integer
#  date             :date
#  value            :decimal(10, 2)
#  net_value        :decimal(10, 2)
#  gloss_value      :decimal(10, 2)
#  document_url     :string
#  refund_number    :string
#  batch_code       :integer
#  tranche          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_expenses_on_deputy_id        (deputy_id)
#  index_expenses_on_expense_type_id  (expense_type_id)
#  index_expenses_on_provider_id      (provider_id)
#

class Expense < ApplicationRecord
  belongs_to :deputy
  belongs_to :expense_type
  belongs_to :provider
end

app/models/expense_type.rb
# == Schema Information
#
# Table name: expense_types
#
#  id              :integer          not null, primary key
#  expense_type_id :integer
#  description     :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ExpenseType < ApplicationRecord
  has_many :expenses
end

app/models/provider.rb
# == Schema Information
#
# Table name: providers
#
#  id         :integer          not null, primary key
#  name       :string
#  cpf_cnpj   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Provider < ApplicationRecord
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deputies_controller.rb
class DeputiesController < ApplicationController
  def index
    @deputies = Deputy.with_total_expenses
                      .order(:name)
  end

  def show
    @deputy = Deputy.find(params[:id])
    @max_expense = @deputy.max_expense
    @expenses = @deputy.expenses.includes(:provider).order(:date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deputies_helper.rb
module DeputiesHelper
end

app/views/deputies/index.html.erb
<table>
  <tr>
    <th>Foto</th>
    <th>Nome</th>
    <th>Despesas</th>
    <th>Detalhes</th>
  </tr>
  <% @deputies.each do |deputy| %>
    <tr>
      <td><%= image_tag "#{deputy.photo_url}", size: '114x152' %></td>
      <td><%= deputy.name %></td>
      <td><%= number_to_currency(deputy.total_expenses, unit: "R$ ", separator: ",", delimiter: ".") %></td>
      <td><%= link_to 'Gastos', deputy_path(deputy.id) %></td>
    </tr>
  <% end %>
</table>

app/views/deputies/show.html.erb
<fieldset>
  <p>
    <%= image_tag "#{@deputy.photo_url}", size: '114x152' %>
  </p>
  <p>
    <strong>Nome:</strong>
    <%= @deputy.name %>
  </p>

  <p>
    <strong>Partido:</strong>
    <%= @deputy.political_party %>
  </p>

  <p>
    <strong>Página:</strong>
    <%= link_to "Perfil", "http://www.camara.leg.br/Internet/deputado/Dep_Detalhe.asp?id=#{@deputy.deputy_id}" %>
  </p>

  <p>
    <strong>Maior Despesa:</strong>
    <%= number_to_currency(@max_expense.net_value, unit: "R$ ", separator: ",", delimiter: ".") %>
    <%= link_to "Cupom", @max_expense.document_url %>
  </p>
</fieldset>

<h2>Despesas</h2>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Estabelecimento</th>
      <th>Valor</th>
      <th>Nota</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.date.strftime("%d/%m/%Y") %></td>
        <td><%= expense.provider.name %></td>
        <td><%= number_to_currency(expense.net_value, unit: "R$ ", separator: ",", delimiter: ".") %></td>
        <td><%= link_to "cupom", expense.document_url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Voltar', deputies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiscalizaDeputados</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1><a href="/" style="text-decoration: none">Fiscaliza Deputados - Ceará</a></h1>
      <p>Ficalize os gastos dos seus deputados.</p>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <p>
        Feito por <a href="https://github.com/gurgelrenan">@gurgelrenan</a>
      </p>
    </footer>
  </body>
</html>